title: Jupyter Notebook
author: Martin Rodriguez
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is prepared to give basic knowledge about the elaboration of notebooks 
  using many styles of writing, images, videos, tables, formulas and others useful tools to make 
  more interesting your information.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  M4rtR0d # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
